version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: rebel-db
    restart: always
    volumes:
      - ./../database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rebel-rootpass
      MYSQL_DATABASE: rebel-dbname
      MYSQL_USER: rebel-dbuser
      MYSQL_PASSWORD: rebel-dbpass
    networks:
      - rebel-network
    
  wordpress:
    image: wordpress:php7.4-fpm-alpine
    container_name: rebel-wordpress
    depends_on:
      - db
    restart: always
    volumes:
      - ./../wp:/var/www/html
    environment:
      WORDPRESS_DB_HOST: rebel-db
      WORDPRESS_DB_USER: rebel-dbuser
      WORDPRESS_DB_PASSWORD: rebel-dbpass
      WORDPRESS_DB_NAME: rebel-dbname
    networks:
      - rebel-network
  
  nginx:
    image: nginx:latest
    container_name: nginx 
    restart: always
    ports: 
      - 8585:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./../wp:/var/www/html
    links:
      - wordpress
    networks:
      - rebel-network

networks:
  rebel-network:
    driver: bridge
